// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// assetSnapshotsDao is the data access object for the table asset_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type assetSnapshotsDao struct {
	*internal.AssetSnapshotsDao
}

var (
	// AssetSnapshots is a globally accessible object for table asset_snapshots operations.
	AssetSnapshots = assetSnapshotsDao{internal.NewAssetSnapshotsDao()}
)

// Add your custom methods and functionality below.
