// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// assetDetailsDao is the data access object for the table asset_details.
// You can define custom methods on it to extend its functionality as needed.
type assetDetailsDao struct {
	*internal.AssetDetailsDao
}

var (
	// AssetDetails is a globally accessible object for table asset_details operations.
	AssetDetails = assetDetailsDao{internal.NewAssetDetailsDao()}
)

// Add your custom methods and functionality below.
