// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// exchangeAccountsDao is the data access object for the table exchange_accounts.
// You can define custom methods on it to extend its functionality as needed.
type exchangeAccountsDao struct {
	*internal.ExchangeAccountsDao
}

var (
	// ExchangeAccounts is a globally accessible object for table exchange_accounts operations.
	ExchangeAccounts = exchangeAccountsDao{internal.NewExchangeAccountsDao()}
)

// Add your custom methods and functionality below.
