// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// exchangeRatesDao is the data access object for the table exchange_rates.
// You can define custom methods on it to extend its functionality as needed.
type exchangeRatesDao struct {
	*internal.ExchangeRatesDao
}

var (
	// ExchangeRates is a globally accessible object for table exchange_rates operations.
	ExchangeRates = exchangeRatesDao{internal.NewExchangeRatesDao()}
)

// Add your custom methods and functionality below.
