// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// goalsDao is the data access object for the table goals.
// You can define custom methods on it to extend its functionality as needed.
type goalsDao struct {
	*internal.GoalsDao
}

var (
	// Goals is a globally accessible object for table goals operations.
	Goals = goalsDao{internal.NewGoalsDao()}
)

// Add your custom methods and functionality below.
