// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// manualAssetsDao is the data access object for the table manual_assets.
// You can define custom methods on it to extend its functionality as needed.
type manualAssetsDao struct {
	*internal.ManualAssetsDao
}

var (
	// ManualAssets is a globally accessible object for table manual_assets operations.
	ManualAssets = manualAssetsDao{internal.NewManualAssetsDao()}
)

// Add your custom methods and functionality below.
