// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// nftCachesDao is the data access object for the table nft_caches.
// You can define custom methods on it to extend its functionality as needed.
type nftCachesDao struct {
	*internal.NftCachesDao
}

var (
	// NftCaches is a globally accessible object for table nft_caches operations.
	NftCaches = nftCachesDao{internal.NewNftCachesDao()}
)

// Add your custom methods and functionality below.
