// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// notificationPreferencesDao is the data access object for the table notification_preferences.
// You can define custom methods on it to extend its functionality as needed.
type notificationPreferencesDao struct {
	*internal.NotificationPreferencesDao
}

var (
	// NotificationPreferences is a globally accessible object for table notification_preferences operations.
	NotificationPreferences = notificationPreferencesDao{internal.NewNotificationPreferencesDao()}
)

// Add your custom methods and functionality below.
