// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// notificationsDao is the data access object for the table notifications.
// You can define custom methods on it to extend its functionality as needed.
type notificationsDao struct {
	*internal.NotificationsDao
}

var (
	// Notifications is a globally accessible object for table notifications operations.
	Notifications = notificationsDao{internal.NewNotificationsDao()}
)

// Add your custom methods and functionality below.
