// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// priceAlertsDao is the data access object for the table price_alerts.
// You can define custom methods on it to extend its functionality as needed.
type priceAlertsDao struct {
	*internal.PriceAlertsDao
}

var (
	// PriceAlerts is a globally accessible object for table price_alerts operations.
	PriceAlerts = priceAlertsDao{internal.NewPriceAlertsDao()}
)

// Add your custom methods and functionality below.
