// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// strategiesDao is the data access object for the table strategies.
// You can define custom methods on it to extend its functionality as needed.
type strategiesDao struct {
	*internal.StrategiesDao
}

var (
	// Strategies is a globally accessible object for table strategies operations.
	Strategies = strategiesDao{internal.NewStrategiesDao()}
)

// Add your custom methods and functionality below.
