// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// syncMetadataDao is the data access object for the table sync_metadata.
// You can define custom methods on it to extend its functionality as needed.
type syncMetadataDao struct {
	*internal.SyncMetadataDao
}

var (
	// SyncMetadata is a globally accessible object for table sync_metadata operations.
	SyncMetadata = syncMetadataDao{internal.NewSyncMetadataDao()}
)

// Add your custom methods and functionality below.
