// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// transactionDailySummariesDao is the data access object for the table transaction_daily_summaries.
// You can define custom methods on it to extend its functionality as needed.
type transactionDailySummariesDao struct {
	*internal.TransactionDailySummariesDao
}

var (
	// TransactionDailySummaries is a globally accessible object for table transaction_daily_summaries operations.
	TransactionDailySummaries = transactionDailySummariesDao{internal.NewTransactionDailySummariesDao()}
)

// Add your custom methods and functionality below.
