// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// unifiedTransactionsDao is the data access object for the table unified_transactions.
// You can define custom methods on it to extend its functionality as needed.
type unifiedTransactionsDao struct {
	*internal.UnifiedTransactionsDao
}

var (
	// UnifiedTransactions is a globally accessible object for table unified_transactions operations.
	UnifiedTransactions = unifiedTransactionsDao{internal.NewUnifiedTransactionsDao()}
)

// Add your custom methods and functionality below.
