// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// userAchievementsDao is the data access object for the table user_achievements.
// You can define custom methods on it to extend its functionality as needed.
type userAchievementsDao struct {
	*internal.UserAchievementsDao
}

var (
	// UserAchievements is a globally accessible object for table user_achievements operations.
	UserAchievements = userAchievementsDao{internal.NewUserAchievementsDao()}
)

// Add your custom methods and functionality below.
