// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// walletAddressesDao is the data access object for the table wallet_addresses.
// You can define custom methods on it to extend its functionality as needed.
type walletAddressesDao struct {
	*internal.WalletAddressesDao
}

var (
	// WalletAddresses is a globally accessible object for table wallet_addresses operations.
	WalletAddresses = walletAddressesDao{internal.NewWalletAddressesDao()}
)

// Add your custom methods and functionality below.
