// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/dao/internal"
)

// webPushSubscriptionsDao is the data access object for the table web_push_subscriptions.
// You can define custom methods on it to extend its functionality as needed.
type webPushSubscriptionsDao struct {
	*internal.WebPushSubscriptionsDao
}

var (
	// WebPushSubscriptions is a globally accessible object for table web_push_subscriptions operations.
	WebPushSubscriptions = webPushSubscriptionsDao{internal.NewWebPushSubscriptionsDao()}
)

// Add your custom methods and functionality below.
