// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/app/risk/dao/internal"
)

// riskMetricsDao is the data access object for the table risk_metrics.
// You can define custom methods on it to extend its functionality as needed.
type riskMetricsDao struct {
	*internal.RiskMetricsDao
}

var (
	// RiskMetrics is a globally accessible object for table risk_metrics operations.
	RiskMetrics = riskMetricsDao{internal.NewRiskMetricsDao()}
)

// Add your custom methods and functionality below.
