// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/app/gas/dao/internal"
)

// gasRecommendationsDao is the data access object for the table gas_recommendations.
// You can define custom methods on it to extend its functionality as needed.
type gasRecommendationsDao struct {
	*internal.GasRecommendationsDao
}

var (
	// GasRecommendations is a globally accessible object for table gas_recommendations operations.
	GasRecommendations = gasRecommendationsDao{internal.NewGasRecommendationsDao()}
)

// Add your custom methods and functionality below.
