// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/app/gas/dao/internal"
)

// gasPriceHistoryDao is the data access object for the table gas_price_history.
// You can define custom methods on it to extend its functionality as needed.
type gasPriceHistoryDao struct {
	*internal.GasPriceHistoryDao
}

var (
	// GasPriceHistory is a globally accessible object for table gas_price_history operations.
	GasPriceHistory = gasPriceHistoryDao{internal.NewGasPriceHistoryDao()}
)

// Add your custom methods and functionality below.
