// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/app/defi/dao/internal"
)

// lendingPositionsDao is the data access object for the table lending_positions.
// You can define custom methods on it to extend its functionality as needed.
type lendingPositionsDao struct {
	*internal.LendingPositionsDao
}

var (
	// LendingPositions is a globally accessible object for table lending_positions operations.
	LendingPositions = lendingPositionsDao{internal.NewLendingPositionsDao()}
)

// Add your custom methods and functionality below.
