// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"your-finance/allfi/internal/app/defi/dao/internal"
)

// lendingRateHistoryDao is the data access object for the table lending_rate_history.
// You can define custom methods on it to extend its functionality as needed.
type lendingRateHistoryDao struct {
	*internal.LendingRateHistoryDao
}

var (
	// LendingRateHistory is a globally accessible object for table lending_rate_history operations.
	LendingRateHistory = lendingRateHistoryDao{internal.NewLendingRateHistoryDao()}
)

// Add your custom methods and functionality below.
